# Generated by Django 4.1.2 on 2022-10-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes_api', '0002_animes_alter_chapters_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='anime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animes_api.animes'),
            preserve_default=False,
        ),
    ]
